services:
  api:
    build:
      dockerfile: Dockerfile
      context: . 
      target: development
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
    ports:
      - '3306:3306'
